source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

# Change 'koja' to match the target in your Xcode project.
target 'koja' do

  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'React', path: '../node_modules/react-native', :subspecs => [
    'Core',
    'BatchedBridge'
  ]

  pod 'GoogleMaps'  # <~~ remove this line if you do not want to support GoogleMaps on iOS

end
